// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBao-UisoHNCFcpWXDl0Na61yVKEb9P608',
    appId: '1:150574670250:web:354aa827674daa7dd5cbd3',
    messagingSenderId: '150574670250',
    projectId: 'darood-app-84a5f',
    authDomain: 'darood-app-84a5f.firebaseapp.com',
    databaseURL: 'https://darood-app-84a5f-default-rtdb.firebaseio.com',
    storageBucket: 'darood-app-84a5f.firebasestorage.app',
    measurementId: 'G-734V5H31DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoaVXa8WeirGUC2hTgt1bnQTz0qKvcOdk',
    appId: '1:150574670250:android:6070011fa5ee420dd5cbd3',
    messagingSenderId: '150574670250',
    projectId: 'darood-app-84a5f',
    databaseURL: 'https://darood-app-84a5f-default-rtdb.firebaseio.com',
    storageBucket: 'darood-app-84a5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgty1JDF2U0QGdrrQF6lbmdT1I3S8kjiY',
    appId: '1:150574670250:ios:e6aba5f8ead85628d5cbd3',
    messagingSenderId: '150574670250',
    projectId: 'darood-app-84a5f',
    databaseURL: 'https://darood-app-84a5f-default-rtdb.firebaseio.com',
    storageBucket: 'darood-app-84a5f.firebasestorage.app',
    iosClientId: '150574670250-25qv49lkiiq7rvek8ivtr778br7poi6b.apps.googleusercontent.com',
    iosBundleId: 'com.abdullahiqbal.dalitask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgty1JDF2U0QGdrrQF6lbmdT1I3S8kjiY',
    appId: '1:150574670250:ios:e6aba5f8ead85628d5cbd3',
    messagingSenderId: '150574670250',
    projectId: 'darood-app-84a5f',
    databaseURL: 'https://darood-app-84a5f-default-rtdb.firebaseio.com',
    storageBucket: 'darood-app-84a5f.firebasestorage.app',
    iosClientId: '150574670250-25qv49lkiiq7rvek8ivtr778br7poi6b.apps.googleusercontent.com',
    iosBundleId: 'com.abdullahiqbal.dalitask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcbdx0eYglY2b2IMMWKjX6jPrEzGnJnHE',
    appId: '1:150574670250:web:f7c6dba9b4ff8615d5cbd3',
    messagingSenderId: '150574670250',
    projectId: 'darood-app-84a5f',
    authDomain: 'darood-app-84a5f.firebaseapp.com',
    databaseURL: 'https://darood-app-84a5f-default-rtdb.firebaseio.com',
    storageBucket: 'darood-app-84a5f.firebasestorage.app',
    measurementId: 'G-ZN123D3QZ4',
  );

}